name: 🚀 Nueva Funcionalidad
description: Proponer una nueva característica o mejora
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Descripción de la funcionalidad
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción
      description: Describe detalladamente la nueva funcionalidad
      placeholder: La funcionalidad consiste en...
    validations:
      required: true
  - type: textarea
    id: requisitos
    attributes:
      label: Requisitos
      description: Lista los requisitos técnicos
      value: |
        - [ ] Requisito 1
        - [ ] Requisito 2
    validations:
      required: true
  - type: textarea
    id: criterios
    attributes:
      label: Criterios de Aceptación
      description: Define cuándo se considerará completada
      value: |
        - [ ] Criterio 1
        - [ ] Criterio 2
    validations:
      required: true
  - type: dropdown
    id: milestone
    attributes:
      label: Etapa
      options:
        - Etapa 1: Diseño Base
        - Etapa 2: Gestión de Recursos
        - Etapa 3: Sistema de Préstamos
        - Etapa 4: Reportes
    validations:
      required: true 